services:
  quiceh-server:
    container_name: quiceh-server
    build:
      context: images/curl_quiceh
    environment:
      - LD_LIBRARY_PATH=/boringssl/lib
      - RUST_LOG=info
    command: "/quiceh/target/performance/quiceh-server --cert /certs/cert.crt --key /certs/cert.key --root /public --listen quiceh-server.quiceh.org:4433"
    networks:
      common_network:
        aliases:
          - quiceh-server.quiceh.org
    ports:
      - "0.0.0.0:4433:4433/udp"

  client:
    container_name: client
    build:
      context: images/curl_quiceh
    environment:
      - LD_LIBRARY_PATH=/boringssl/lib:/quiceh/target/performance
      - RUST_LOG=info
      - DISPLAY
    privileged: true
    tty: true
    networks:
      - common_network
    volumes:
      - ./perf_record:/perf_record
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri

networks:
  common_network: {}
